### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by oTfGVa** [WeAllJS/weallbehave#10]

**Comment by oTfGVa** [comment]
contributing guidelines

**Comment by oTfGVa** [comment]
If you're working in the shared repository model, we recommend that you use a topic branch for your pull request. While you can send pull requests from any branch or commit, with a topic branch you can push follow-up commits if you need to update your proposed changes.
Be very careful when force pushing commits to a pull request. Force pushing changes the repository history and can corrupt your pull request. If other collaborators branch the project before a force push, the force push may overwrite commits that collaborators based their work on.

**Comment by oTfGVa** [comment]
If you're working in the shared repository model, we recommend that you use a topic branch for your pull request. While you can send pull requests from any branch or commit, with a topic branch you can push follow-up commits if you need to update your proposed changes.
Be very careful when force pushing commits to a pull request. Force pushing changes the repository history and can corrupt your pull request. If other collaborators branch the project before a force push, the force push may overwrite commits that collaborators based their work on.

**Comment by oTfGVa** [comment]
changes.

If you're working in the shared repository model, we recommend that you use a topic branch for your pull request. While you can send pull requests from any branch or commit, with a topic branch you can push follow-up commits if you need to update your proposed

**Comment by oTfGVa** [comment]
Thank you so much for your interest in contributing!. All types of contributions are encouraged and valued. See below for different ways to help, and details about how this project handles them!

Please make sure to read the

**Comment by aredridel** [comment]
? What's the intent of this issue?

**Comment by oTfGVa** [comment]
okay I understand now thk you

**Comment by aredridel** [comment]
Not sure what this is, we can reopen if needed.

**Comment by oTfGVa** [comment]
really project

**Comment by oTfGVa** [comment]
commented [2 days ago](https://github.com/WeAllJS/weallbehave/issues/10#issuecomment-1778512714)
Thank you so much for your interest in contributing!. All types of contributions are encouraged and valued. See below for different ways to help, and details about how this project handles them!

Please make sure to read the

**Comment by oTfGVa** [comment]
commented [2 days ago](https://github.com/WeAllJS/weallbehave/issues/10#issuecomment-1778512714)
Thank you so much for your interest in contributing!. All types of contributions are encouraged and valued. See below for different ways to help, and details about how this project handles them!

Please make sure to read the

**Comment by oTfGVa** [comment]
commented [2 days ago](https://github.com/contributing!. All types of contributions are encouraged and valued. See below for different ways to help, and details about how this project handles them!

Please make sure to read the

**Comment by oTfGVa** [comment]
commented [2 days ago](https://github.com/WeAllJS/weallbehave/issues/10#issuecomment-1778512714)
Thank you so much for your interest in contributing!. All types of contributions are encouraged and valued. See below for different ways to help, and details about how this project handles them!

Please make sure to read the

**Comment by oTfGVa** [comment]
commented [2 days ago](https://github.com/WeAllJS/weallbehave/issues/10#issuecomment-1778512714)
Thank you so much for your interest in contributing!. All types of contributions are encouraged and valued. See below for different ways to help, and details about how this project handles them!

Please make sure to read the
